name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: bundle-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Set up yarn
      run: |
        npm i yarn
    - name: Install packages
      run: |
        sudo apt-get install -y libsqlite3-dev
    - name: Install gems
      run: |
        bundle -j 4 --path vendor/bundle
    - name: Install node modules
      run: |
        yarn
    - name: Build
      run: |
        bin/rails db:setup assets:precompile
    - name: Run test
      run: |
        bin/rails test
    - name: Run system test
      run: |
        bin/rails test:system
