name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Set up yarn
      run: |
        npm i yarn
    - name: Install packages
      run: |
        sudo apt-get install -y libsqlite3-dev
    - name: Build
      run: |
        bundle -j 4
        bin/rails yarn:install db:setup assets:precompile
    - name: Run test
      run: |
        bin/rails test
    - name: Run system test
      run: |
        bin/rails test:system
